language: php

php:
- 7.1
- 7.2

before_script: composer -n --prefer-source install --dev

script: vendor/bin/phpunit --coverage-clover clover

after_success:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover